### ISSUE TITLE
Remove Handlebars

### ISSUE THREAD

**Issue by gordonmzhu** [gordonmzhu/exercises#7]
In a comment below, post a link to a live demo (e.g. Glitch URL) to your app without Handlebars.

**Comment by p5-yz** [comment]
https://glitch.com/edit/#!/decisive-goal?path=public/js/app.js:1:0

**Comment by roostad** [comment]
https://glitch.com/~todomvc-rewrite

**Comment by WayneHaworth** [comment]
[https://ash-sneezeweed.glitch.me](https://ash-sneezeweed.glitch.me)

**Comment by DahneDuffy** [comment]
https://glitch.com/~dahne-app-js-remove-handlebars

**Comment by Tcbyco** [comment]
https://glitch.com/~mixolydian-valley

**Comment by quickreactor** [comment]
https://glitch.com/~beautiful-list

**Comment by mariagus** [comment]
https://glitch.com/~equal-stargazer

**Comment by NaeNate** [comment]
https://q-no-handlebars.glitch.me

**Comment by smr310** [comment]
https://glitch.com/edit/#!/wool-grain?path=public/js/app.js:8:13

**Comment by MichelangeloAbsoluto** [comment]
https://glitch.com/~merciful-acaibowl-

**Comment by TannerChrishop** [comment]
https://glitch.com/~spotty-oceanic-drawbridge

**Comment by stsoiasue** [comment]
https://glitch.com/~great-olive-archeology

**Comment by jnykim** [comment]
https://glitch.com/~wealthy-peridot-hardware

**Comment by mikebabz426** [comment]
https://glitch.com/edit/undefined#!/so-long-jquery?path=public/js/app.js:184:6

**Comment by kca485** [comment]
https://glitch.com/~metal-wary-professor

**Comment by shengng325** [comment]
https://glitch.com/~todomvc-nts

**Comment by ShelbyEliza** [comment]
https://glitch.com/~intelligent-evening-screen

**Comment by pongchanok014** [comment]
https://glitch.com/~remove-handlebar-paul-pong

**Comment by dnlbellfield** [comment]
https://glitch.com/~remove-handlebar-s

**Comment by rosenYordanov** [comment]
https://glitch.com/~goofy-tidy-saver

**Comment by bpkiel** [comment]
https://glitch.com/~hazel-fair-bulb

**Comment by Lyle27** [comment]
https://glitch.com/~rem-handlebars

**Comment by feetonground** [comment]
https://glitch.com/~fabulous-fuchsia-chasmosaurus

**Comment by nacafaca** [comment]
https://glitch.com/~longing-grey-tailor

**Comment by ssagar19** [comment]
https://glitch.com/edit/#!/pattern-biplane?path=public/js/app.js:212:6

**Comment by Emery13** [comment]
https://glitch.com/~tin-protective-september

**Comment by powerfrost** [comment]
https://glitch.com/~wnc-reading-exercise-4

Used JavaScript template literals.

**Comment by Kayige** [comment]
https://glitch.com/~cookie-sage-expansion

combined the past 2 exercises code with this.

**Comment by blkdm0n** [comment]
https://glitch.com/~woozy-gregarious-square

**Comment by Bjoern-Again** [comment]
https://glitch.com/~lumbar-water-cauliflower

**Comment by lrybakova** [comment]
https://glitch.com/~ivory-pool-almanac

**Comment by brettpoarch** [comment]
https://glitch.com/~fast-sudsy-fin

**Comment by Nethmal** [comment]
https://glitch.com/~fluttering-ambiguous-willow

**Comment by ellypham** [comment]
https://sticky-concise-drink.glitch.me/#/all

**Comment by akinaohira** [comment]
https://glitch.com/~ludicrous-periwinkle-glitter

**Comment by login3b7e** [comment]
https://glitch.com/edit/#!/cyan-agreeable-ball

**Comment by santanaG** [comment]
https://glitch.com/~dandelion-bedecked-property

That was fun.

**Comment by Dringr** [comment]
https://glitch.com/~east-fluff-period

**Comment by JeffReuther** [comment]
https://glitch.com/~remove-handlebars-jr

**Comment by mikrubashkin** [comment]
https://glitch.com/~mik-remove-handlebars

**Comment by jakeMulhern** [comment]
https://glitch.com/~cool-sphynx-nohandlebars

**Comment by tyeness** [comment]
https://glitch.com/~mt-remove-handlebars

**Comment by chrisjbrinson** [comment]
https://glitch.com/~meteor-stone-party

**Comment by johnpurcell514** [comment]
https://glitch.com/~reinvented-conscious-quilt

**Comment by martysaid** [comment]
https://glitch.com/~wac--remove-handlebars

**Comment by acostae4** [comment]
https://glitch.com/~pewter-purring-flute

**Comment by cespe** [comment]
The demo: https://achieved-classic-astrodon.glitch.me/#/all

The code: https://glitch.com/edit/#!/achieved-classic-astrodon?path=public%2Fjs%2Fapp.js%3A225%3A7

**Comment by cespe** [comment]
> https://glitch.com/~pewter-purring-flute

I like the way you handled the footer, it's cleaner than what I did.

**Comment by gkl-gkl** [comment]
https://glitch.com/~alkaline-removing-handlebars

This gave me a really tough time but it was worthwhile.

**Comment by pravinthedeveloper** [comment]
https://glitch.com/edit/#!/tangible-sequoia-yumberry?path=public%2Fjs%2Fapp.js%3A2%3A0

**Comment by by-masen** [comment]
https://glitch.com/~watchandcode-remove-handlebars

**Comment by muzz00ka** [comment]
https://glitch.com/edit/#!/secret-cloudy-venom?path=index.html%3A18%3A49

**Comment by tomashugo** [comment]
https://carnelian-poised-trillium.glitch.me

**Comment by feline-blue** [comment]
https://glitch.com/~spiced-intelligent-stock

**Comment by dklear** [comment]
https://glitch.com/~dklear-todo-nohandlebars
implemented using template literals

**Comment by mandorlinoGitHub** [comment]
https://glitch.com/~mandor-remove-handlebars-1

**Comment by jnlar** [comment]
https://glitch.com/~remove-handlebars-wac

**Comment by diegomouradev** [comment]
[](https://todomvc-remove-handlebars-diego.glitch.me)

**Comment by imrebartis** [comment]
https://glitch.com/~todomc-remove-handlebars-imre

**Comment by tyreke5994** [comment]
https://glitch.com/~remove-hbars

**Comment by ng1235** [comment]
https://glitch.com/~elite-pincushion-xw7ghkf6fj

**Comment by dannyeldridge** [comment]
https://glitch.com/edit/#!/hammerhead-alpine-gym

**Comment by cvansteenburg** [comment]
https://glitch.com/~todomvc-no-handlebars-cv
Add one to the template literal parade! Also, Range.createContextualFragment() is very useful. This was a great exercise.

**Comment by adkissonpaul** [comment]
https://glitch.com/~hospitable-cyber-quotation

**Comment by ElSguidge** [comment]
https://glitch.com/~marks99--handlebars

**Comment by Doctor-Stupid** [comment]
https://glitch.com/~chivalrous-inexpensive-spruce

**Comment by abbysudario** [comment]
https://glitch.com/~cuboid-dolomite-sceptre

**Comment by abbysudario** [comment]
https://glitch.com/~receptive-mighty-farm

**Comment by dnlbellfield** [comment]
https://glitch.com/~trail-little-handle

**Comment by jclay7683** [comment]
https://glitch.com/~witty-torch-soul

Kinda ugly long code in some places, but it works!

**Comment by LennartSakowsky** [comment]
https://glitch.com/~todomvc-remove-handlebars

**Comment by daveyoon64** [comment]
https://glitch.com/~mangrove-zinc-tapir

<3 template literals

**Comment by ruslan-azarov** [comment]
https://glitch.com/edit/#!/v4-rigorous-harmonious-damselfly

**Comment by CarlosRCoelho** [comment]
https://remo-handlebars-2.glitch.me - **Live App**
https://glitch.com/~remo-handlebars-2 - **Project Page**

**Comment by jeremysiegel** [comment]
https://dramatic-steep-mackerel.glitch.me/#/all

**Comment by retro2115** [comment]
https://glitch.com/~chivalrous-crystal-hide
